### ISSUE TITLE
Tutorial doesn't run on latest code.

### ISSUE THREAD

**Issue by ashwinphatak** [cosmos/sdk-application-tutorial#135] opened 2019-09-06 08:41 UTC
When running the [tutorial](https://github.com/cosmos/sdk-application-tutorial/blob/master/tutorial/build-run.md) locally, the `nscli query nameservice resolve jack.id` command doesn't work. I'd tried the same a few days back (before the update to update to sdk 0.37) and it worked then.

```
$ nscli query nameservice resolve jack.id
could not resolve name - jack.id 
```

Error in the nsd console:

```
I[2019-09-06|14:05:07.634] Committed state                              module=state height=7 txs=0 appHash=3B051114B03B6B10C2CA9125091AB0CF037294A876F71F5F3C21AB39329ED554
I[2019-09-06|14:05:12.655] Executed block                               module=state height=8 validTxs=0 invalidTxs=1
I[2019-09-06|14:05:12.660] Committed state                              module=state height=8 txs=1 appHash=4B8EDA374F491A1B77F5F9321485B198729EC2B608BC2C296502FB132B6AB592
E[2019-09-06|14:05:16.317] Panic in RPC HTTP handler                    module=rpc-server err="interface conversion: interface is nil, not types.KVStore" stack="goroutine 193 [running]:\nruntime/debug.Stack(0xc000268ed0, 0xfe5ea0, 0xc0026132c0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1.1(0xc0025feb20, 0x14e26e0, 0xc000add980, 0xbf54a47112e8a093, 0xa3e924c6a, 0x1ce8400, 0xc000a5d400)\n\t/home/ashwinp/go/pkg/mod/github.com/tendermint/tendermint@v0.32.2/rpc/lib/server/http_server.go:161 +0x486\npanic(0xfe5ea0, 0xc0026132c0)\n\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\ngithub.com/cosmos/cosmos-sdk/store/cachemulti.Store.GetKVStore(...)\n\t/home/ashwinp/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.0/store/cachemulti/store.go:143\ngithub.com/cosmos/cosmos-sdk/types.Context.KVStore(0x14e1c20, 0xc00003a120, 0x14f1f00, 0xc0025737c0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/home/ashwinp/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.0/types/context.go:200 +0x89\ngithub.com/cosmos/sdk-application-tutorial/x/nameservice/internal/keeper.Keeper.GetWhois(0x14f4880, 0xc0003621c0, 0x14d3200, 0x0, 0xc000108150, 0x14e1c20, 0xc00003a120, 0x14f1f00, 0xc0025737c0, 0xa, ...)\n\t/home/ashwinp/projects/wireline/sdk-application-tutorial/x/nameservice/internal/keeper/keeper.go:30 +0x98\ngithub.com/cosmos/sdk-application-tutorial/x/nameservice/internal/keeper.Keeper.ResolveName(...)\n\t/home/ashwinp/projects/wireline/sdk-application-tutorial/x/nameservice/internal/keeper/keeper.go:57\ngithub.com/cosmos/sdk-application-tutorial/x/nameservice/internal/keeper.queryResolve(0x14e1c20, 0xc00003a120, 0x14f1f00, 0xc0025737c0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/home/ashwinp/projects/wireline/sdk-application-tutorial/x/nameservice/internal/keeper/querier.go:36 +0x100\ngithub.com/cosmos/sdk-application-tutorial/x/nameservice/internal/keeper.NewQuerier.func1(0x14e1c20, 0xc00003a120, 0x14f1f00, 0xc0025737c0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/home/ashwinp/projects/wireline/sdk-application-tutorial/x/nameservice/internal/keeper/querier.go:23 +0x213\ngithub.com/cosmos/cosmos-sdk/baseapp.handleQueryCustom(0xc0000c2900, 0xc002573780, 0x4, 0x4, 0x1d05818, 0x0, 0x0, 0xc000adf020, 0x22, 0x8, ...)\n\t/home/ashwinp/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.0/baseapp/baseapp.go:601 +0x5c9\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Query(0xc0000c2900, 0x1d05818, 0x0, 0x0, 0xc000adf020, 0x22, 0x0, 0x0, 0x0, 0x0, ...)\n\t/home/ashwinp/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.0/baseapp/baseapp.go:463 +0x2e8\ngithub.com/tendermint/tendermint/abci/client.(*localClient).QuerySync(0xc000095500, 0x1d05818, 0x0, 0x0, 0xc000adf020, 0x22, 0x0, 0x0, 0x0, 0x0, ...)\n\t/home/ashwinp/go/pkg/mod/github.com/tendermint/tendermint@v0.32.2/abci/client/local_client.go:207 +0x10e\ngithub.com/tendermint/tendermint/proxy.(*appConnQuery).QuerySync(0xc000329270, 0x1d05818, 0x0, 0x0, 0xc000adf020, 0x22, 0x0, 0x0, 0x0, 0x0, ...)\n\t/home/ashwinp/go/pkg/mod/github.com/tendermint/tendermint@v0.32.2/proxy/app_conn.go:143 +0x6a\ngithub.com/tendermint/tendermint/rpc/core.ABCIQuery(0xc0025feb60, 0xc000adf020, 0x22, 0x1d05818, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/home/ashwinp/go/pkg/mod/github.com/tendermint/tendermint@v0.32.2/rpc/core/abci.go:57 +0x114\nreflect.Value.call(0xff1180, 0x1331440, 0x13, 0x1137474, 0x4, 0xc002589e80, 0x5, 0x5, 0x5, 0x18, ...)\n\t/usr/local/go/src/reflect/value.go:460 +0x5f6\nreflect.Value.Call(0xff1180, 0x1331440, 0x13, 0xc002589e80, 0x5, 0x5, 0x4, 0x4, 0x0)\n\t/usr/local/go/src/reflect/value.go:321 +0xb4\ngithub.com/tendermint/tendermint/rpc/lib/server.makeJSONRPCHandler.func1(0x14dd220, 0xc0025feb20, 0xc000a5d400)\n\t/home/ashwinp/go/pkg/mod/github.com/tendermint/tendermint@v0.32.2/rpc/lib/server/handlers.go:157 +0x905\ngithub.com/tendermint/tendermint/rpc/lib/server.handleInvalidJSONRPCPaths.func1(0x14dd220, 0xc0025feb20, 0xc000a5d400)\n\t/home/ashwinp/go/pkg/mod/github.com/tendermint/tendermint@v0.32.2/rpc/lib/server/handlers.go:181 +0x9c\nnet/http.HandlerFunc.ServeHTTP(0xc000329430, 0x14dd220, 0xc0025feb20, 0xc000a5d400)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\nnet/http.(*ServeMux).ServeHTTP(0xc000499800, 0x14dd220, 0xc0025feb20, 0xc000a5d400)\n\t/usr/local/go/src/net/http/server.go:2387 +0x1bd\ngithub.com/tendermint/tendermint/rpc/lib/server.maxBytesHandler.ServeHTTP(0x14c5160, 0xc000499800, 0xf4240, 0x14dd220, 0xc0025feb20, 0xc000a5d400)\n\t/home/ashwinp/go/pkg/mod/github.com/tendermint/tendermint@v0.32.2/rpc/lib/server/http_server.go:206 +0xcf\ngithub.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1(0x14dd920, 0xc0000e36c0, 0xc000a5d400)\n\t/home/ashwinp/go/pkg/mod/github.com/tendermint/tendermint@v0.32.2/rpc/lib/server/http_server.go:179 +0x33f\nnet/http.HandlerFunc.ServeHTTP(0xc000306c30, 0x14dd920, 0xc0000e36c0, 0xc000a5d400)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\nnet/http.serverHandler.ServeHTTP(0xc0003636c0, 0x14dd920, 0xc0000e36c0, 0xc000a5d400)\n\t/usr/local/go/src/net/http/server.go:2802 +0xa4\nnet/http.(*conn).serve(0xc002210820, 0x14e1be0, 0xc002573600)\n\t/usr/local/go/src/net/http/server.go:1890 +0x875\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2927 +0x38e\n"
I[2019-09-06|14:05:17.678] Executed block                               module=state height=9 validTxs=0 invalidTxs=0
I[2019-09-06|14:05:17.682] Committed state                              module=state height=9 txs=0 appHash=5A53A6A462301CAA4497B4C2C8260A229044ADEF5CCE3F4D06BEACD25D18ECA3
I[2019-09-06|14:05:22.701] Executed block                               module=state height=10 validTxs=0 invalidTxs=0

```

The earlier transactions seem to have gone through fine:

```
$ nscli tx nameservice buy-name jack.id 5nametoken --from jack
{
  "chain_id": "namechain",
  "account_number": "0",
  "sequence": "1",
  "fee": {
    "amount": [],
    "gas": "200000"
  },
  "msgs": [
    {
      "type": "nameservice/BuyName",
      "value": {
        "name": "jack.id",
        "bid": [
          {
            "denom": "nametoken",
            "amount": "5"
          }
        ],
        "buyer": "cosmos1qltywk7mrvry0yl4al64ez8h32yrhkgzjkr2rf"
      }
    }
  ],
  "memo": ""
}

confirm transaction before signing and broadcasting [y/N]: y
Password to sign with 'jack':
{
  "height": "0",
  "txhash": "2A82587409EFEEB5C0918128A83E055C3A93E0DBDC07C5208A2046005E7F0E8D",
  "raw_log": "[{\"msg_index\":0,\"success\":true,\"log\":\"\"}]",
  "logs": [
    {
      "msg_index": 0,
      "success": true,
      "log": ""
    }
  ]
}


$ nscli tx nameservice set-name jack.id 8.8.8.8 --from jack
{
  "chain_id": "namechain",
  "account_number": "0",
  "sequence": "2",
  "fee": {
    "amount": [],
    "gas": "200000"
  },
  "msgs": [
    {
      "type": "nameservice/SetName",
      "value": {
        "name": "jack.id",
        "value": "8.8.8.8",
        "owner": "cosmos1qltywk7mrvry0yl4al64ez8h32yrhkgzjkr2rf"
      }
    }
  ],
  "memo": ""
}

confirm transaction before signing and broadcasting [y/N]: y
Password to sign with 'jack':
{
  "height": "0",
  "txhash": "250910CD9814C8E78290F1B65E01755B6C726444C615B91B67EBEEA4FDBF3BA1",
  "raw_log": "[{\"msg_index\":0,\"success\":true,\"log\":\"\"}]",
  "logs": [
    {
      "msg_index": 0,
      "success": true,
      "log": ""
    }
  ]
}

```

**Comment by patrickwieth** [comment] 2019-09-09 05:36
Hi,

after upgrading my app to cosmos-sdk 0.37 I found out that all custom transactions are reported as "success": true in nscli, but are listed as invalidtx in nsd. So I cloned this tutorial again and found out the very same as above. 
So I would like to add, that the transactions are going through fine is not correct here. This is only displayed by nscli, nsd shows invalid transactions:

> I[2019-09-07|12:22:52.851] Executed block                               module=state height=14 validTxs=0 invalidTxs=1
I[2019-09-07|12:22:52.862] Committed state                              module=state height=14 txs=1 appHash=B2C1C8716E2649401D4086BCB2EAAEB4365AD5197246D63522D2871CFB072A98

This is the case for buy-name as well as set-name. Since these transactions are invalid, resolve fails, because the name is not set. So maybe this info helps, that it's not the query that has a problem but the transactions.

**Comment by patrickwieth** [comment] 2019-09-10 10:45
I don't understand why this is closed. The behavior is still the same. The txs are shown as invalid and the resolve doesn't work or is it just me?

**Comment by marbar3778** [comment] 2019-09-10 11:23
Seems the pr that was merged closed it. Sorry for that

**Comment by hschoenburg** [comment] 2019-09-10 15:44
Here is the fix https://github.com/cosmos/sdk-application-tutorial/commit/eb120663fd74b5b5b05e93f67b1336d053ab1d80

**Comment by patrickwieth** [comment] 2019-09-10 16:07
I'm confused. The bug described here still remains for me after pull, make install and repeating all the init stuff. 
![Screenshot_2019-09-07_18-34-09](https://user-images.githubusercontent.com/10943178/64630558-aaf2d500-d3f5-11e9-9871-57ba0af441a1.png)

The screenshot shows the output of nsd, red circle indicates invalidtx form set-name (the same happens for buy-name), the bottom terminal shows succesful response from nscli and could not resolve from the query.
For you guys this behavior has ended after the last merge?

**Comment by marbar3778** [comment] 2019-09-10 19:33
I was able to recreate the issue the most recent merge didnt fully solve the probelm

**Comment by hschoenburg** [comment] 2019-09-10 21:18
eeek sorry guys. I thought I had it fixed. Back to the drawing board.

**Comment by hschoenburg** [comment] 2019-09-10 22:03
hmm ok I did a full rebuild (deleted .nsd and .nscli, ran make install) and I cant reproduce using master. `buy-name`, `set-name`, `resolve` and `whois` work  fine for me.....
<img width="866" alt="Screen Shot 2019-09-10 at 3 01 39 PM" src="https://user-images.githubusercontent.com/144207/64653726-12039000-d3dc-11e9-986d-7441d0087407.png">
<img width="1216" alt="Screen Shot 2019-09-10 at 3 01 27 PM" src="https://user-images.githubusercontent.com/144207/64653734-16c84400-d3dc-11e9-8b0b-92653e48e8da.png">

**Comment by marbar3778** [comment] 2019-09-11 05:54
So it works for me now. I think the issue is that when you set name it's trying to set a name that hasn't been bought yet so it can't find anything. The cli should return failure with an error message instead of success

**Closed by marbar3778** 2019-09-11 05:54 UTC

**Comment by patrickwieth** [comment] 2019-09-11 08:23
I tried it on a freshly installed VM and it works. So sorry for bothering you after it was fixed. On my other system it doesn't work, I tried nsd unsafe-reset-all, rm .nsd and even deleting go/pkg and I dunno what remains in my system, that causes this behavior o_O
